services:
  app:
    build: .
    ports:
      - "5001:5001"
    env_file:
      - .env
    volumes:
      - .:/app
    command: python run.py --mode api-only
    depends_on:
      - redis

  redis:
    image: redis/redis-stack:latest
    ports:
      - "6379:6379"
      - "8001:8001"  # RedisInsight web interface
    restart: unless-stopped
    volumes:
      - redis_data:/data

volumes:
  redis_data: